name: Simple Echo Workflow

# Define when the workflow should be triggered
on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Triggers the workflow on pull request to the main branch

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: print hello
        run: echo hello kamesh


  echo_job: # job-name
    # The type of machine to run on (GitHub-hosted runner)
    runs-on: ubuntu-latest

    steps:
      # Downloading the code from repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Print "Hello, World!" to the log
      - name: Print Message
        shell: bash
        run: echo "Hello, World Madhu!"

      - name: Print workspace
        run: echo ${{ github.workspace }}

      - name: Print directory inside
        run: |
          ls -al

      - name: Print all varialbes in github context
        run: |
            echo ${{ github.repository }}
            echo ${{ github.repository_owner }}
            echo ${{ github.event_name }}
            echo ${{ github.ref }}
            echo ${{ github.sha }}
            echo ${{ github.run_id }}
            echo ${{ github.run_number }}
            echo ${{ github.actor }}
            echo ${{ github.workflow }}
            echo ${{ github.workspace }}
            echo ${{ github.event }}


      - name: Print all varialbes in runner context
        run: |
            echo ${{ runner.os }}
            echo ${{ runner.arch }}
            echo ${{ runner.temp }}
            echo ${{ runner.workspace }}